apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dbserver1.inventory.products
  namespace: amq-streams-cdc
  labels:
    strimzi.io/cluster: cdc-cluster
    app.kubernetes.io/part-of: amq-streams-cdc-demo
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-configs
  namespace: amq-streams-cdc
  labels:
    strimzi.io/cluster: cdc-cluster
    app.kubernetes.io/part-of: amq-streams-cdc-demo
spec:
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-offsets
  namespace: amq-streams-cdc
  labels:
    strimzi.io/cluster: cdc-cluster
    app.kubernetes.io/part-of: amq-streams-cdc-demo
spec:
  partitions: 25
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-status
  namespace: amq-streams-cdc
  labels:
    strimzi.io/cluster: cdc-cluster
    app.kubernetes.io/part-of: amq-streams-cdc-demo
spec:
  partitions: 5
  replicas: 3
  config:
    cleanup.policy: compact

