apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: amq-streams-cdc
  labels:
    app: mysql
    app.kubernetes.io/part-of: amq-streams-cdc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: amq-streams-cdc
  labels:
    app: postgres
    app.kubernetes.io/part-of: amq-streams-cdc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

